FROM golang:1.24.3-alpine3.21 AS builder

WORKDIR /usr/local/source/

COPY ./go.mod ./go.sum ./
RUN go mod download

COPY ./cmd/sso ./cmd
# COPY ./pkg ./pkg
COPY ./internal ./internal

RUN go build -ldflags="-s -w" -o /usr/local/bin/app ./cmd/

FROM alpine:3.21

USER 1000:1000

COPY --from=builder /usr/local/bin/app /app

ENTRYPOINT [ "/app" ]