// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

type UserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepository) EXPECT() *UserRepository_Expecter {
	return &UserRepository_Expecter{mock: &_m.Mock}
}

// CheckUserIsAdminByID provides a mock function with given fields: _a0, _a1
func (_m *UserRepository) CheckUserIsAdminByID(_a0 context.Context, _a1 string) (bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CheckUserIsAdminByID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_CheckUserIsAdminByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckUserIsAdminByID'
type UserRepository_CheckUserIsAdminByID_Call struct {
	*mock.Call
}

// CheckUserIsAdminByID is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *UserRepository_Expecter) CheckUserIsAdminByID(_a0 interface{}, _a1 interface{}) *UserRepository_CheckUserIsAdminByID_Call {
	return &UserRepository_CheckUserIsAdminByID_Call{Call: _e.mock.On("CheckUserIsAdminByID", _a0, _a1)}
}

func (_c *UserRepository_CheckUserIsAdminByID_Call) Run(run func(_a0 context.Context, _a1 string)) *UserRepository_CheckUserIsAdminByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepository_CheckUserIsAdminByID_Call) Return(_a0 bool, _a1 error) *UserRepository_CheckUserIsAdminByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_CheckUserIsAdminByID_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *UserRepository_CheckUserIsAdminByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
