CREATE TABLE IF NOT EXISTS user_roles (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role TEXT NOT NULL REFERENCES roles(role) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role)
);
